### PR TITLE
fix sign of BB spectrum term in EB response

### PR DESCRIPTION
**Pull request by cmbant**

### CODE REVIEW

**Comment by JulienPeloton** [comment]
Thanks @cmbant for fixing this error! Do you know what would be the impact of this change? I remember we always had the highest level of mismatch concerning the BB & EB terms in 1611.01446 (sims vs theory).

**Comment by JulienPeloton** [comment]
Looking at the equation, I guess the impact scales as CB/CE, so more pronounced at very small scales where lensing is the dominant part of both spectra?

**Comment by cmbant** [comment]
I think it's about 1-2% in the phi responses for S4. I didn't look at how it enters as a function of ell_cmb.

**Comment by JulienPeloton** [comment]
Thanks! Merging.

**Pull request merged**
